// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CartItem: typeof import('./src/components/CartItem.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    OrderItem: typeof import('./src/components/OrderItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WareItem: typeof import('./src/components/WareItem.vue')['default']
  }
}

export {}
